# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circunscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nEscanos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('circunscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleccion.Circunscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.IntegerField(default=0)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleccion.Mesa')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eleccion.Partido')),
            ],
        ),
    ]
